Mod2Project/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :armies 
  resources :army_units
  # resources :army_units do 
  #   resources :armies 
  # end 

  resources :units 
  resources :unit_types 
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Mod2Project/app/models/army_unit.rb
class ArmyUnit < ApplicationRecord
belongs_to :army 
belongs_to :unit



    




end

Mod2Project/app/models/unit.rb
class Unit < ApplicationRecord
belongs_to :unit_type 
has_many :army_units 
has_many :armies, through: :army_units 


    def unit_stats 
        "#{name} - Price: #{price} - Attack: #{attack} - Defence: #{defence}"
    end 




end

Mod2Project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Mod2Project/app/controllers/armies_controller.rb
class ArmiesController < ApplicationController

    def index 
        @armies = Army.all 
    end 
    
    def new 
        @army = Army.new 
    end 

    def create 
        @army = Army.create(army_params)
        redirect_to new_army_unit_path
    end 

    def show 
        @army = Army.find(params[:id])
    end 


    # def edit 
    #     @army = Army.find(params[:id])
    #     redirect_to edit_army_unit_path
    # end 

    # def update 
    #     @army = Army.find(params[:id])
    #     @army.update(army_params)
         
        
    # end

    def destroy
        Army.find(params[:id]).destroy
    end
    
    private 

    def army_params 
        params.require(:army).permit(:name, :user_id)
    end 


end

Mod2Project/app/controllers/army_units_controller.rb
class ArmyUnitsController < ApplicationController


    def new 
        @army_unit = ArmyUnit.new 
        unit_type_general = UnitType.find(1)
        @general_units = Unit.all.select{|u| u.unit_type == unit_type_general }
        unit_type_infantry = UnitType.find(2)
        @infantry_units = Unit.all.select{|u| u.unit_type == unit_type_infantry }
        unit_type_cavalry = UnitType.find(3)
        @cavalry_units = Unit.all.select{|u| u.unit_type == unit_type_cavalry }
        unit_type_missile = UnitType.find(4) 
        @missile_units = Unit.all.select{|u| u.unit_type == unit_type_missile }
        unit_type_artillery = UnitType.find(5) 
        @artillery_units = Unit.all.select{|u| u.unit_type == unit_type_artillery }
    end 

    def create 
        @army_unit = ArmyUnit.create(army_unit_params)
        #LOOK AT NESTED ROUTING?
        redirect_to army_unit.army 
    end 

    def show 
        @army_unit = ArmyUnit.find(params[:id])
    end 

    def edit 
        @army_unit = ArmyUnit.find(params[:id]) 
    end 

    def update 
        @army_unit = ArmyUnit.find(params[:id])
        @army_unit.update(army_unit_params)
        # redirect_to
    end 


    private 

    def army_unit_params 
        params.require(:army_unit).permit(:army_id, :unit_id)
    end 






end

Mod2Project/app/controllers/units_controller.rb
class UnitsController < ApplicationController

    
    def new 
        @unit = Unit.new 
    end 

    def create 
        @unit = Unit.create(unit_params)
    end 



    private 

    def unit_params 
        params.require(:unit).permit(:name, :size, :price, :attack, :defence, :unit_type_id)
    end 
end

Mod2Project/app/controllers/users_controller.rb
class UsersController < ApplicationController


    def new 
        @user = User.new 
    end 
        
    def create 
        @user = User.create(user_params)
        redirect_to user_path(@user)
    end 

    def show 
        @user = User.find(params[:id])
        @armies = Army.all

    end 

    private 

    def user_params 
        params.require(:user).permit(:name)
    end 



end

Mod2Project/app/views/armies/new.html.erb
<%= form_for (@army) do |f| %> 
    <h1><label> Please enter the name of your forces: </label><br></h1>
    <%= f.text_field :name %> 
    
    

    <%= f.submit %> 
<% end %>




    
     

Mod2Project/app/views/armies/show.html.erb
<h1> </h1> 

Mod2Project/app/views/army_units/edit.html.erb
h1> EDIT YOUR UNITS! </h1>
<%= form_for (@army_unit) do |f| %> 
<h2>Choose your General</h2>
<%= f.collection_select :unit_id, @general_units, :id, :name, {:prompt => 'General'} %><br>
<h2>Choose your Infantry Units</h2> 
<%= f.collection_check_boxes :unit_id, @infantry_units, :id, :name, {:prompt => 'Infantry'} %><br>
<h2>Choose your Cavalry Units</h2> 
<%= f.collection_check_boxes :unit_id, @cavalry_units, :id, :name, {:prompt => 'Cavalry'} %><br>
<h2>Choose your Missle Unit</h2> 
<%= f.collection_select :unit_id, @missile_units, :id, :name, {:prompt => 'Missile'} %><br>
<h2>Choose your Artillery Unit</h2> 
<%= f.collection_select :unit_id, @artillery_units, :id, :name, {:prompt => 'Artillery'} %><br>
<%= f.submit %>
<% end %>  

Mod2Project/app/views/army_units/new.html.erb
<h1> Select Your Units</h1>
<%= form_for (@army_unit) do |f| %> 
<h2>Choose your General</h2>
<%= f.collection_select :unit_id, @general_units, :id, :unit_stats, {:prompt => 'General'} %><br>
<h2>Choose your Infantry Units</h2> 
<%= f.collection_check_boxes :unit_id, @infantry_units, :id, :unit_stats %><br>
<h2>Choose your Cavalry Units</h2> 
<%= f.collection_check_boxes :unit_id, @cavalry_units, :id, :unit_stats %><br>
<h2>Choose your Missile Unit</h2> 
<%= f.collection_select :unit_id, @missile_units, :id, :unit_stats, {:prompt => 'Missile'} %><br>
<h2>Choose your Artillery Unit</h2> 
<%= f.collection_select :unit_id, @artillery_units, :id, :unit_stats, {:prompt => 'Artillery'} %><br>
<%= f.submit %>
<% end %>  


<img src = "https://www.honga.net/totalwar/rome2/images/rome2/flags/rome/mon_256.png" alt = "Rome" >
<img src = "https://www.honga.net/totalwar/rome2/images/rome2/flags/carthage/mon_256.png" alt = "Carthage" >
<img src = "https://www.honga.net/totalwar/rome2/images/rome2/flags/seleucid/mon_256.png" alt = "Seleucid" > 
<img src = "https://www.honga.net/totalwar/rome2/images/rome2/flags/sparta/mon_256.png" alt = "Sparta" >
<img src = "https://www.honga.net/totalwar/rome2/images/rome2/flags/arverni/mon_256.png" alt = "Gaul" > 

Mod2Project/app/views/army_units/show.html.erb
<h1>YOUR ARMY</h1>

Mod2Project/app/views/users/new.html.erb
<%= form_for (@user) do |f| %> 
    <label> Please enter your name: </label> 
    <%= f.text_field :name %>
    <%= f.label :user_id %> 
      
    

    <%= f.submit %> 
<% end %>

Mod2Project/app/views/users/show.html.erb
<h1> Welcome <%= @user.name %></h1> 

<p>“You have power over your mind - not outside events. Realize this, and you will find strength.”
― Marcus Aurelius, Meditations</p>

<% @user.armies.each do |army| %>
    <div class="army">
      <span><%= army.name %></span>
    <%= link_to "Edit", edit_army_path(army), method: :edit %> - <%= link_to "Delete", army_path(army), method: :delete, data: { confirm: "Really?" } %>
    </div>
    <% end %>

<h3><%= link_to "Create A New Army", new_army_path %></h3>